version: 2
jobs:
  build:
    docker:
    - image: circleci/node:8.9.1
    working_directory: ~/circleCI
    steps:
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules  # location depends on npm version
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
    
      - checkout

      - run:
          name : Install modules
          command : npm install

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date

      - run :
          name : run build
          command : npm run build

      - run :
          name : install aws
          command : sudo pip install awscli --upgrade --user

      - run :
          name : Deplay to S3
          command : aws s3 sync /dist s3://seed-kau.com

# workflows : 
#   version: 2
#   build-deploy:
#     jobs:
#       - deploy:
#         filters:
#           branches :
#             only : master