version: 2
jobs:
  build:
    docker:
    - image: circleci/node:8.9.1
    working_directory: ~/circleCI
    steps:
      - checkout

      - run:
          name : Install modules
          command : npm install

      - run :
          name : run build
          command : npm run build

      - run:
            name: Install awscli
            command: sudo apt-get -y -qq install awscli
      - run:
          name: Deploy to S3
          command: aws s3 sync dist/ s3://seed-kau.com --delete
  # deploy:
  #     docker:
  #       - image: circleci/python:2.7-jessie
  #     working_directory: ~/circleCI
  #     steps:
  #       - checkout

workflows:
  version: 2
  build-deploy:
    jobs:
      - build :
            filters:
                  branches:
                    only: master
      # - deploy:
      #     requires:
      #       - build
          
